/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "snw_shard_service.h"

gboolean
snw_shard_service_if_shard_map (snwShardServiceIf *iface, GHashTable ** _return, const gchar * type, const gdouble version, const gchar * token, snwInvalidOperation ** ouch, GError **error)
{
  return SNW_SHARD_SERVICE_IF_GET_INTERFACE (iface)->shard_map (iface, _return, type, version, token, ouch, error);
}

gboolean
snw_shard_service_if_get_object_id (snwShardServiceIf *iface, gchar ** _return, const gchar * message, const gdouble version, const gchar * token, snwInvalidOperation ** ouch, GError **error)
{
  return SNW_SHARD_SERVICE_IF_GET_INTERFACE (iface)->get_object_id (iface, _return, message, version, token, ouch, error);
}

GType
snw_shard_service_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (snwShardServiceIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "snwShardServiceIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
snw_shard_service_if_interface_init (snwShardServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (snwShardServiceClient, snw_shard_service_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (SNW_TYPE_SHARD_SERVICE_IF,
                                                snw_shard_service_if_interface_init))

enum _snwShardServiceClientProperties
{
  PROP_0,
  PROP_SNW_SHARD_SERVICE_CLIENT_INPUT_PROTOCOL,
  PROP_SNW_SHARD_SERVICE_CLIENT_OUTPUT_PROTOCOL
};

void
snw_shard_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  snwShardServiceClient *client = SNW_SHARD_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_SNW_SHARD_SERVICE_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_SNW_SHARD_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
snw_shard_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  snwShardServiceClient *client = SNW_SHARD_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_SNW_SHARD_SERVICE_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_SNW_SHARD_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean snw_shard_service_client_send_shard_map (snwShardServiceIf * iface, const gchar * type, const gdouble version, const gchar * token, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SNW_SHARD_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "shardMap", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "shardMap_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "type", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, type, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "version", T_DOUBLE, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_double (protocol, version, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "token", T_STRING, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, token, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean snw_shard_service_client_recv_shard_map (snwShardServiceIf * iface, GHashTable ** _return, snwInvalidOperation ** ouch, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SNW_SHARD_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "shardMap", 8) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected shardMap", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_MAP)
          {
            {
              guint32 size;
              guint32 i;
              ThriftType key_type;
              ThriftType value_type;

              /* read the map begin marker */
              if ((ret = thrift_protocol_read_map_begin (protocol, &key_type, &value_type, &size, error)) < 0)
                return 0;
              xfer += ret;

              /* iterate through each of the map's fields */
              for (i = 0; i < size; i++)
              {
                gint64* key8 = g_new (gint64, 1);
                GHashTable * val9 = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, g_free);
                if ((ret = thrift_protocol_read_i64 (protocol, &*key8, error)) < 0)
                  return 0;
                xfer += ret;
                {
                  guint32 size;
                  guint32 i;
                  ThriftType key_type;
                  ThriftType value_type;

                  /* read the map begin marker */
                  if ((ret = thrift_protocol_read_map_begin (protocol, &key_type, &value_type, &size, error)) < 0)
                    return 0;
                  xfer += ret;

                  /* iterate through each of the map's fields */
                  for (i = 0; i < size; i++)
                  {
                    gchar * key10 = NULL;
                    gchar * val11 = NULL;
                    if (key10 != NULL)
                    {
                      g_free(key10);
                      key10 = NULL;
                    }

                    if ((ret = thrift_protocol_read_string (protocol, &key10, error)) < 0)
                      return 0;
                    xfer += ret;
                    if (val11 != NULL)
                    {
                      g_free(val11);
                      val11 = NULL;
                    }

                    if ((ret = thrift_protocol_read_string (protocol, &val11, error)) < 0)
                      return 0;
                    xfer += ret;
                    if (val9 && key10)
                      g_hash_table_insert ((GHashTable *)val9, (gpointer) key10, (gpointer) val11);
                  }

                  /* read the map end marker */
                  if ((ret = thrift_protocol_read_map_end (protocol, error)) < 0)
                    return 0;
                  xfer += ret;
                }
                if (*_return && key8)
                  g_hash_table_insert ((GHashTable *)*_return, (gpointer) key8, (gpointer) val9);
              }

              /* read the map end marker */
              if ((ret = thrift_protocol_read_map_end (protocol, error)) < 0)
                return 0;
              xfer += ret;
            }
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (SNW_TYPE_INVALID_OPERATION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, SNW_INVALID_OPERATION_ERROR, SNW_INVALID_OPERATION_ERROR_CODE, "InvalidOperation");
      return FALSE;
  }
  return TRUE;
}

gboolean snw_shard_service_client_shard_map (snwShardServiceIf * iface, GHashTable ** _return, const gchar * type, const gdouble version, const gchar * token, snwInvalidOperation ** ouch, GError ** error)
{
  if (!snw_shard_service_client_send_shard_map (iface, type, version, token, error))
    return FALSE;
  if (!snw_shard_service_client_recv_shard_map (iface, _return, ouch, error))
    return FALSE;
  return TRUE;
}

gboolean snw_shard_service_client_send_get_object_id (snwShardServiceIf * iface, const gchar * message, const gdouble version, const gchar * token, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SNW_SHARD_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "getObjectId", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "getObjectId_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "message", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, message, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "version", T_DOUBLE, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_double (protocol, version, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "token", T_STRING, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, token, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean snw_shard_service_client_recv_get_object_id (snwShardServiceIf * iface, gchar ** _return, snwInvalidOperation ** ouch, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SNW_SHARD_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "getObjectId", 11) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected getObjectId", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_string (protocol, &*_return, error)) < 0)
              return 0;
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ouch != NULL)
            {
              g_object_unref (*ouch);
            }
            *ouch = g_object_new (SNW_TYPE_INVALID_OPERATION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ouch), protocol, error)) < 0)
            {
              g_object_unref (*ouch);
              *ouch = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ouch != NULL)
  {
      g_set_error (error, SNW_INVALID_OPERATION_ERROR, SNW_INVALID_OPERATION_ERROR_CODE, "InvalidOperation");
      return FALSE;
  }
  return TRUE;
}

gboolean snw_shard_service_client_get_object_id (snwShardServiceIf * iface, gchar ** _return, const gchar * message, const gdouble version, const gchar * token, snwInvalidOperation ** ouch, GError ** error)
{
  if (!snw_shard_service_client_send_get_object_id (iface, message, version, token, error))
    return FALSE;
  if (!snw_shard_service_client_recv_get_object_id (iface, _return, ouch, error))
    return FALSE;
  return TRUE;
}

static void
snw_shard_service_if_interface_init (snwShardServiceIfInterface *iface)
{
  iface->shard_map = snw_shard_service_client_shard_map;
  iface->get_object_id = snw_shard_service_client_get_object_id;
}

static void
snw_shard_service_client_init (snwShardServiceClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
snw_shard_service_client_class_init (snwShardServiceClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = snw_shard_service_client_set_property;
  gobject_class->get_property = snw_shard_service_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_SNW_SHARD_SERVICE_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_SNW_SHARD_SERVICE_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
snw_shard_service_handler_shard_service_if_interface_init (snwShardServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (snwShardServiceHandler, 
                         snw_shard_service_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (SNW_TYPE_SHARD_SERVICE_IF,
                                                snw_shard_service_handler_shard_service_if_interface_init))

gboolean snw_shard_service_handler_shard_map (snwShardServiceIf * iface, GHashTable ** _return, const gchar * type, const gdouble version, const gchar * token, snwInvalidOperation ** ouch, GError ** error)
{
  g_return_val_if_fail (SNW_IS_SHARD_SERVICE_HANDLER (iface), FALSE);

  return SNW_SHARD_SERVICE_HANDLER_GET_CLASS (iface)->shard_map (iface, _return, type, version, token, ouch, error);
}

gboolean snw_shard_service_handler_get_object_id (snwShardServiceIf * iface, gchar ** _return, const gchar * message, const gdouble version, const gchar * token, snwInvalidOperation ** ouch, GError ** error)
{
  g_return_val_if_fail (SNW_IS_SHARD_SERVICE_HANDLER (iface), FALSE);

  return SNW_SHARD_SERVICE_HANDLER_GET_CLASS (iface)->get_object_id (iface, _return, message, version, token, ouch, error);
}

static void
snw_shard_service_handler_shard_service_if_interface_init (snwShardServiceIfInterface *iface)
{
  iface->shard_map = snw_shard_service_handler_shard_map;
  iface->get_object_id = snw_shard_service_handler_get_object_id;
}

static void
snw_shard_service_handler_init (snwShardServiceHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
snw_shard_service_handler_class_init (snwShardServiceHandlerClass *cls)
{
  cls->shard_map = NULL;
  cls->get_object_id = NULL;
}

enum _snwShardServiceProcessorProperties
{
  PROP_SNW_SHARD_SERVICE_PROCESSOR_0,
  PROP_SNW_SHARD_SERVICE_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (snwShardServiceProcessor,
               snw_shard_service_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* snwShardServiceProcessorProcessFunction) (snwShardServiceProcessor *, 
                                                              gint32,
                                                              ThriftProtocol *,
                                                              ThriftProtocol *,
                                                              GError **);

typedef struct
{
  gchar *name;
  snwShardServiceProcessorProcessFunction function;
} snw_shard_service_processor_process_function_def;

static gboolean
snw_shard_service_processor_process_shard_map (snwShardServiceProcessor *,
                                               gint32,
                                               ThriftProtocol *,
                                               ThriftProtocol *,
                                               GError **);
static gboolean
snw_shard_service_processor_process_get_object_id (snwShardServiceProcessor *,
                                                   gint32,
                                                   ThriftProtocol *,
                                                   ThriftProtocol *,
                                                   GError **);

static snw_shard_service_processor_process_function_def
snw_shard_service_processor_process_function_defs[2] = {
  {
    "shardMap",
    snw_shard_service_processor_process_shard_map
  },
  {
    "getObjectId",
    snw_shard_service_processor_process_get_object_id
  }
};

static gboolean
snw_shard_service_processor_process_shard_map (snwShardServiceProcessor *self,
                                               gint32 sequence_id,
                                               ThriftProtocol *input_protocol,
                                               ThriftProtocol *output_protocol,
                                               GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  snwShardServiceShardMapArgs * args =
    g_object_new (SNW_TYPE_SHARD_SERVICE_SHARD_MAP_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gchar * type;
    gdouble version;
    gchar * token;
    snwInvalidOperation * ouch = NULL;
    GHashTable * return_value;
    snwShardServiceShardMapResult * result_struct;

    g_object_get (args,
                  "type", &type,
                  "version", &version,
                  "token", &token,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (SNW_TYPE_SHARD_SERVICE_SHARD_MAP_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (snw_shard_service_handler_shard_map (SNW_SHARD_SERVICE_IF (self->handler),
                                             &return_value,
                                             type,
                                             version,
                                             token,
                                             &ouch,
                                             error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_hash_table_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "shardMap",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "shardMap",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("ShardService.shardMap implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "shardMap",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (type != NULL)
      g_free (type);
    if (token != NULL)
      g_free (token);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
snw_shard_service_processor_process_get_object_id (snwShardServiceProcessor *self,
                                                   gint32 sequence_id,
                                                   ThriftProtocol *input_protocol,
                                                   ThriftProtocol *output_protocol,
                                                   GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  snwShardServiceGetObjectIdArgs * args =
    g_object_new (SNW_TYPE_SHARD_SERVICE_GET_OBJECT_ID_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gchar * message;
    gdouble version;
    gchar * token;
    snwInvalidOperation * ouch = NULL;
    gchar * return_value;
    snwShardServiceGetObjectIdResult * result_struct;

    g_object_get (args,
                  "message", &message,
                  "version", &version,
                  "token", &token,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (SNW_TYPE_SHARD_SERVICE_GET_OBJECT_ID_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (snw_shard_service_handler_get_object_id (SNW_SHARD_SERVICE_IF (self->handler),
                                                 &return_value,
                                                 message,
                                                 version,
                                                 token,
                                                 &ouch,
                                                 error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_free (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "getObjectId",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ouch != NULL)
      {
        g_object_set (result_struct,
                      "ouch", ouch,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "getObjectId",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("ShardService.getObjectId implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "getObjectId",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (message != NULL)
      g_free (message);
    if (token != NULL)
      g_free (token);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
snw_shard_service_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                           ThriftProtocol *input_protocol,
                                           ThriftProtocol *output_protocol,
                                           gchar *method_name,
                                           gint32 sequence_id,
                                           GError **error)
{
  snw_shard_service_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  snwShardServiceProcessor *self = SNW_SHARD_SERVICE_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (SNW_SHARD_SERVICE_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    g_free (method_name);
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
snw_shard_service_processor_set_property (GObject *object,
                                          guint property_id,
                                          const GValue *value,
                                          GParamSpec *pspec)
{
  snwShardServiceProcessor *self = SNW_SHARD_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_SNW_SHARD_SERVICE_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
snw_shard_service_processor_get_property (GObject *object,
                                          guint property_id,
                                          GValue *value,
                                          GParamSpec *pspec)
{
  snwShardServiceProcessor *self = SNW_SHARD_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_SNW_SHARD_SERVICE_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
snw_shard_service_processor_dispose (GObject *gobject)
{
  snwShardServiceProcessor *self = SNW_SHARD_SERVICE_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (snw_shard_service_processor_parent_class)->dispose (gobject);
}

static void
snw_shard_service_processor_finalize (GObject *gobject)
{
  snwShardServiceProcessor *self = SNW_SHARD_SERVICE_PROCESSOR (gobject);

  thrift_safe_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (snw_shard_service_processor_parent_class)->finalize (gobject);
}

static void
snw_shard_service_processor_init (snwShardServiceProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 2; index += 1)
    g_hash_table_insert (self->process_map,
                         snw_shard_service_processor_process_function_defs[index].name,
                         &snw_shard_service_processor_process_function_defs[index]);
}

static void
snw_shard_service_processor_class_init (snwShardServiceProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = snw_shard_service_processor_dispose;
  gobject_class->finalize = snw_shard_service_processor_finalize;
  gobject_class->set_property = snw_shard_service_processor_set_property;
  gobject_class->get_property = snw_shard_service_processor_get_property;

  dispatch_processor_class->dispatch_call = snw_shard_service_processor_dispatch_call;
  cls->dispatch_call = snw_shard_service_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    SNW_TYPE_SHARD_SERVICE_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_SNW_SHARD_SERVICE_PROCESSOR_HANDLER,
                                   param_spec);
}
